@startuml SaborBrasileiro - Diagrama de Caso de Uso

left to right direction
skinparam packageStyle rectangle
skinparam nodesep 30
skinparam ranksep 60
scale 1.3

actor Cliente
actor Cozinheiro
actor Entregador

rectangle "SaborBrasileiro" {

  rectangle "Área do Cliente" {
    usecase "Cadastrar-se" as UC01c
    usecase "Buscar pratos" as UC03
    usecase "Realizar pedido" as UC04
    usecase "Efetuar pagamento" as UC05
    usecase "Aplicar cupom de desconto" as UC05b
    usecase "Acompanhar pedido" as UC09
    usecase "Avaliar pedido" as UC08
  }

  rectangle "Área do Cozinheiro" {
    usecase "Cadastrar-se " as UC01k
    usecase "Gerenciar cardápio" as UC02
    usecase "Gerenciar pedidos recebidos" as UC06
  }

  rectangle "Área do Entregador" {
    usecase "Cadastrar-se  " as UC01e
    usecase "Realizar entrega" as UC07
  }
}

Cliente --> UC01c
Cliente --> UC03
Cliente --> UC04
Cliente --> UC09
Cliente --> UC08
UC04 .> UC05 : <<include>>
UC05b .> UC04 : <<extend>>

Cozinheiro --> UC01k
Cozinheiro --> UC02
Cozinheiro --> UC06

Entregador --> UC01e
Entregador --> UC07

@enduml
